export const webhookSubscriptionTopics = [
  'APP_UNINSTALLED',
  'SUBSCRIPTION_CONTRACTS_CREATE',
  'SUBSCRIPTION_CONTRACTS_ACTIVATE',
  'SUBSCRIPTION_CONTRACTS_PAUSE',
  'SUBSCRIPTION_CONTRACTS_CANCEL',
  'SUBSCRIPTION_BILLING_CYCLES_SKIP',
  'SUBSCRIPTION_BILLING_ATTEMPTS_SUCCESS',
  'SUBSCRIPTION_BILLING_ATTEMPTS_FAILURE',
  'SELLING_PLAN_GROUPS_CREATE',
  'SELLING_PLAN_GROUPS_UPDATE',
];
